### ISSUE TITLE
[FeatureRequest]: Add url for cloud build when the build starts

### ISSUE THREAD

**Issue by racinmat** [avast/wanna-ml#71]
### Contact Details

matej.racinsky@gendigital.com

### Is your feature request related to a problem? Please describe

When the cloud build of the image starts, I must manually navigate to it in the browser if I want to see the progress.

### Describe the solution you'd like

In the output, e.g.
```bash
✅ Reading and validating wanna yaml config
ℹ GCP profile 'wanna-dev' will be used.
ℹ Profile details: profile_name='wanna-dev' project_id='...' zone='europe-west1-b' region='europe-west1' labels=None bucket='...' service_account='...' network='...'
subnet='...' kms_key=None docker_repository='wanna-dev' docker_registry=None env_vars=None
ℹ Building train_serve_all docker image in GCP Cloud build
```
I would like to see the linkhttps://console.cloud.google.com/cloud-build/builds;region=europe-west1?project=...

The same would be nice for the JupyterLab in Vertex AI Workbench

**Comment by jsilva** [comment]
Featured added to the 0.3.3 release
